--- 
networks: 
  iobroker-network: 
    driver: bridge
services: 
  iobroker: 
    build: ./iobroker
    container_name: iobroker
    depends_on: 
      - mysql
      - redis-prod
    hostname: iobroker
    links: 
      - redis-prod
      - mysql
    networks: 
      - iobroker-network
    ports: 
      - "1880:1880"
      - "2001:2001"
      - "8081:8081"
      - "8282:8282"
      - "8088:8088"
      - "8284:8284"
    privileged: true
    restart: always
    stdin_open: true
    tty: true
    volumes: 
      - "/opt/iobroker:/opt/iobroker"
  mysql: 
    container_name: mysql
    environment: 
      MYSQL_ROOT_PASSWORD: Test1234
      MYSQL_ROOT_HOST: %
    expose: 
      - "3306"
      - "33060"
    image: "mysql"
    networks: 
      - iobroker-network
    ports: 
      - "3306:3306"
      - "33060:33060"
    restart: always
    volumes: 
      - "./mysql/init.sql:/docker-entrypoint-initdb.d/iobroker-init.sql"
      - "/docker/mysql/data:/var/lib/mysql"
  redis-prod: 
    command: "redis-server /usr/local/etc/redis/redis.conf"
    container_name: redis-prod
    image: redis
    networks: 
      - iobroker-network
    ports: 
      - "6379:6379"
    restart: always
    volumes: 
      - "/docker/redis/redis.conf:/usr/local/etc/redis/redis.conf"
      - "/docker/redis/data:/data"
version: "3"
